[package]
name = "ratatable"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.29.0"
env_logger = "0.11.8"
log = "0.4.29"
ratatui = "0.30.0"
russh = "0.57.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
terminput = "0.5.12"
terminput-crossterm = "0.4.8"
tokio = { version = "1.49.0", features = ["full"] }
# wraptatui = { path = "../wraptatui" }
wraptatui = { git = "https://github.com/lasernoises/wraptatui.git" }
